[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config = "1.6.1"
aws-sdk-s3 = "1.82.0"
clap = { version = "4.5.36", features = ["derive"] }
dotenv = "0.15.0"
tokio = { version = "1.44.2", features = ["full"] }
